### PR TITLE
Install missing Java dependency for Jenkins and add Docker support

### PR DESCRIPTION
**Pull request by maksimluzik**
possibility to run docker-compose and other docker commands from Jenkins
installed Java 8 that is required for Jenkins to actually work

### CODE REVIEW

**Comment by edinc** [comment]
@maksimluzik Sorry for the slow response. I'm just seeing this. Will review your PR as soon as I get some time :)

**Comment by edinc** [comment]
@maksimluzik After another half a year 🙈 back at this. I've merged another PR which includes the missing Java installation. If you still have time to resolve the conflicts I would gladly merge your Docker implementation in.

**Comment by maksimluzik** [comment]
@edinc Merge issues resolved

**Review by edinc — APPROVED** [review]

**Comment by edinc** [comment]
@maksimluzik Cool. Approved and merged.
Thank you very much for your contribution!

**Pull request merged**
